[package]
name = "guile-sys-2018"
version = "0.1.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "guile_sys"
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.42.2"
